### ISSUE TITLE
Error:(9, 10) Groovyc: Only classes and closures can be used for attribute 'value' in @grails.test.mixin.TestFor

### ISSUE THREAD

**Issue by Bulletninja** [mathifonseca/grails-browser-detection#11]
I keep getting this error when building.
I only use added the plugin and got that as a consequence. 

> Error:(9, 10) Groovyc: Only classes and closures can be used for attribute 'value' in @grails.test.mixin.TestFor

**Comment by Bulletninja** [comment]
file content i get the error from :

```
package browserdetection.UserAgentIdentService

import grails.test.mixin.TestFor
import spock.lang.Specification

/**
 * See the API for {@link grails.test.mixin.services.ServiceUnitTestMixin} for usage instructions
 */
@TestFor(GroovyService)
class GroovyServiceSpec extends Specification {

    def setup() {
    }

    def cleanup() {
    }

    void "test something"() {
    }
}

```

**Comment by mathifonseca** [comment]
Hi @Bulletninja, not sure if this issue is related to the plugin. Does that `GroovyService` exist?

**Comment by Bulletninja** [comment]
You are right, something weird happened to intelliJ. I regenerated everything and it worked without changing anything else.
